variable "instance_count" {}
variable "instance_type" {}
variable "public_sg" {}
variable "public_subnet" {}
variable "vol_size" {}
variable "key_name" {}
variable "public_key_path" {}
variable "user_data_path" {}
variable "dbendpoint" {}
variable "dbuser" {}
variable "dbpassword" {}
variable "dbname" {}
variable "tg_port" {}
variable "lb_target_group_arn" {}
